EMAIL SENDING: 	2015-06-13-09:00:21

EMAIL SENDING SUCCESS: 	2015-06-13-09:00:25

Monitor Finished.   Monitor Time: 2015-06-13-09:00:25.   Time Cost: 0'23"
------------------------------------------------------------------------------

------------------------------------------------------------------------------
EMAIL SENDING: 	2015-06-14-09:00:18

EMAIL SENDING SUCCESS: 	2015-06-14-09:00:19

Monitor Finished.   Monitor Time: 2015-06-14-09:00:19.   Time Cost: 0'18"
------------------------------------------------------------------------------

------------------------------------------------------------------------------
Access Error: http://www.ccdi.gov.cn/jlsc/index_1.html	2015-06-14-22:12:34
Traceback (most recent call last):
  File "/home/cnnic/monitorURL/myUtils.py", line 970, in eachCriterion
    sourceCode  = urllib2.urlopen(req).read()
  File "/usr/lib/python2.7/urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 410, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 523, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 448, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 531, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 521: 

Access Error: http://www.isra.org.cn/news/index.htm	2015-06-14-22:12:34
Traceback (most recent call last):
  File "/home/cnnic/monitorURL/myUtils.py", line 970, in eachCriterion
    sourceCode  = urllib2.urlopen(req).read()
  File "/usr/lib/python2.7/urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 410, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 523, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 448, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 531, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 404: Not Found

Access Error: https://www.powerdns.com/news/news-archive.html	2015-06-14-22:12:39
Traceback (most recent call last):
  File "/home/cnnic/monitorURL/myUtils.py", line 970, in eachCriterion
    sourceCode  = urllib2.urlopen(req).read()
  File "/usr/lib/python2.7/urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 410, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 523, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 448, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 531, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 404: Not Found

Access Error: http://www.dotasia.org/index.html	2015-06-14-22:12:42
Traceback (most recent call last):
  File "/home/cnnic/monitorURL/myUtils.py", line 970, in eachCriterion
    sourceCode  = urllib2.urlopen(req).read()
  File "/usr/lib/python2.7/urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 410, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 523, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 442, in error
    result = self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 629, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/usr/lib/python2.7/urllib2.py", line 410, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 523, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 448, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 531, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 404: Not Found

Access Error: http://www.cnvd.org.cn/	2015-06-14-22:16:25
Traceback (most recent call last):
  File "/home/cnnic/monitorURL/myUtils.py", line 970, in eachCriterion
    sourceCode  = urllib2.urlopen(req).read()
  File "/usr/lib/python2.7/urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 410, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 523, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 448, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 531, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 502: Bad Gateway

lxw_Timed Out: http://www.cnvd.org.cn/	2015-06-14-22:17:55

Monitor Finished.   Monitor Time: 2015-06-14-22:17:55.   Time Cost: 1'1"
------------------------------------------------------------------------------

------------------------------------------------------------------------------
Monitor Finished.   Monitor Time: 2015-06-14-22:25:21.   Time Cost: 0'1"
------------------------------------------------------------------------------

------------------------------------------------------------------------------
